### ISSUE TITLE
Exit code 0 when an unhandled exception occurs in jdnssec-verify

### ISSUE THREAD

**Issue by SvenVD-be** [dblacka/jdnssec-tools#10]
Hi,

We are using this in our tests and are using the exit code to see if the jdnssec-verify passed it's test.

Now, when there is an unhandled exception (like this one: https://github.com/dblacka/jdnssec-tools/issues/9) then it exits with code 0, so this goes unnoticed for us.

Suggestion is to have a catch all for all exceptions in jdnssec-verify  and to exit with non-zero code in that case.

Thanks

**Comment by dblacka** [comment]
I just added a System.exit(1) to the command line base class (CLBase), so all of the tools should exit with 1 if they throw an exception.
